# Generated by Django 5.2.7 on 2025-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_code',
            field=models.URLField(),
        ),
    ]
